name: ScoreMania

on: [push, pull_request]

jobs:
  build:
    name: Build ScoreMania
    runs-on: ubuntu-latest
    steps:
      # Activate
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: C:/Users/Omar/Desktop/CSC 4111/ScoreMania/Library
          key: Library-ScoreMania-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-ScoreMania-
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: C:/Users/Omar/Desktop/CSC 4111/ScoreMania
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: 
            - StandaloneWindows64
            - iOS
            - Androids

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build