name: Build ScoreMania

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build ScoreMania for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
    steps:
      # Activate
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: C:/Users/Omar/Desktop/CSC 4111/ScoreMania/Library
          key: Library-ScoreMania-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-ScoreMania-
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: C:/Users/Omar/Desktop/CSC 4111/ScoreMania
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}